---
- name: "create virtualenv"
  command: virtualenv env chdir={{project_root}} creates={{project_env}}/bin/activate

- name: "set virtualenv owner"
  command: chown -R zeratul:zeratul env chdir={{project_root}}
